# Generated by Django 3.1 on 2020-12-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Categories name')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Cilent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120, verbose_name='FIO')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone_number')),
                ('tg_number', models.CharField(max_length=20, verbose_name='tg username or phone number')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_status', models.BooleanField(verbose_name='categories status')),
                ('product_status', models.BooleanField(verbose_name='product status')),
                ('client_status', models.BooleanField(verbose_name='Clients status')),
                ('order_status', models.BooleanField(verbose_name='order status')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product name')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='price')),
                ('debt', models.FloatField(blank=True, default=None, null=True, verbose_name='debt')),
                ('count', models.IntegerField(verbose_name='count')),
                ('categoriya_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, verbose_name='Count')),
                ('sum', models.FloatField(blank=True, default=None, null=True, verbose_name='summa')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='qarz olgan vaqti')),
                ('cilent_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.cilent')),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user.product')),
            ],
        ),
    ]
