# Generated by Django 3.1 on 2020-12-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoriya_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
