# Generated by Django 3.1 on 2020-12-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201209_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_categories',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='categories_status',
            field=models.BooleanField(default=True, verbose_name='categories status'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='client_status',
            field=models.BooleanField(default=True, verbose_name='Clients status'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='order_status',
            field=models.BooleanField(default=True, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='product_status',
            field=models.BooleanField(default=True, verbose_name='product status'),
        ),
    ]
